### ISSUE TITLE
Missing icon on iOS <=14

### ISSUE THREAD

**Issue by CySxL** [PoomSmart/TrollLEDs#1]
As title.

Already rebuilded icon caches.

![image](https://github.com/PoomSmart/TrollLEDs/assets/15531137/caaa7b18-9035-4814-a048-658c9ca5a344)

**Comment by PoomSmart** [comment]
@CySxL Does version 1.1.1 fix it?

**Comment by CySxL** [comment]
@PoomSmart sadly no 
![image](https://github.com/PoomSmart/TrollLEDs/assets/15531137/09b7839b-e8a8-42b6-9571-a27cbb092ac3)

**Comment by PoomSmart** [comment]
Did you rebuild the icon caches via TrollStore?

**Comment by CySxL** [comment]
yes literally using TrollStore to rebuild icon cache.

But my TrollStore is 2.0.8, would that be the culprit?

**Comment by PoomSmart** [comment]
TS version probably doesn't matter. So after you rebuilt the icon caches, did you run `uicache` too? @CySxL

**Comment by PoomSmart** [comment]
Also, can you see if the app icons are inside `TrollLEDs.app` in your fs?

**Comment by CySxL** [comment]
> TS version probably doesn't matter. So after you rebuilt the icon caches, did you run `uicache` too? @CySxL 

Haven't done that. Will try it now.

**Comment by CySxL** [comment]
> TS version probably doesn't matter. So after you rebuilt the icon caches, did you run `uicache` too? @CySxL 

Also tried: uicache, rebuild icon cache in TS, respring, and reboot userspace after all of them. Still no luck.

**Comment by CySxL** [comment]
> Also, can you see if the app icons are inside `TrollLEDs.app` in your fs?

@PoomSmart Yeah, but there are some of the PNGs are 0kb. So I guess we found the issue.

![image](https://github.com/PoomSmart/TrollLEDs/assets/15531137/4f706830-b8b1-4df0-9d45-a2e3f067ad0d)

![image](https://github.com/PoomSmart/TrollLEDs/assets/15531137/eca260e4-bd7e-4c23-83fb-1f71784630d7)

![image](https://github.com/PoomSmart/TrollLEDs/assets/15531137/1bd75db6-4d9e-44f1-9370-1fde8ae735f6)

**Comment by CySxL** [comment]
Also it's kinda like this issue: https://github.com/donato-fiore/TrollDecrypt/issues/2

Hope that helps xd

**Comment by PoomSmart** [comment]
I don't recall TrollLEDs has this many app icons.

**Comment by CySxL** [comment]
> I don't recall TrollLEDs has this many app icons. It only has two.

Yeah somehow it duplicates itself on iOS 14 device like what I had with TrollDecryptor.

**Comment by PoomSmart** [comment]
@CySxL I suggest you uninstall the app and install the latest version (1.1.1) again.

**Comment by CySxL** [comment]
Yeah I just tried that haha. Uninstalled and reinstalled.

Video: https://streamable.com/0jwewr

**Comment by PoomSmart** [comment]
I see, Theos duplicates the icons.

**Comment by PoomSmart** [comment]
Fixed in v1.1.2

**Comment by CySxL** [comment]
Feel bad to say... but 1.1.2 is still having the same issue on my device 🥲

**Comment by PoomSmart** [comment]
@CySxL I made sure that there are two icons in `TrollLEDs.app`, that's why the file size was reduced to just 50 KB.

What's inside your `TrollLEDs.app` now?

**Comment by CySxL** [comment]
> What's inside your `TrollLEDs.app` now?

@PoomSmart Seems like they all now disappear

![image](https://github.com/PoomSmart/TrollLEDs/assets/15531137/2c164037-cf7b-44cc-b901-2d16916a188a)

**Comment by PoomSmart** [comment]
Yeah that's expected and it should work now, no?

**Comment by PoomSmart** [comment]
By the way, you should rebuild the icon caches before doing `uicache -a`

**Comment by CySxL** [comment]
> Yeah that's expected and it should work now, no?

Sadly not working for me.

![image](https://github.com/PoomSmart/TrollLEDs/assets/15531137/e4e5c3ad-b293-4f49-bb61-c2878291fc59)

**Comment by PoomSmart** [comment]
@CySxL I will connect you via Discord

**Comment by CySxL** [comment]
Gotcha! I just saw a friend request, is that you? 😂😅

**Comment by CySxL** [comment]
Fixed in 1.2.1

Thanks @PoomSmart ❤️
